### ISSUE TITLE
Ability to create CCS Matrix with 0x0 dimension

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#1]
Hi,
How are you? 
I think it would be good if library does not throw exception if someone wants to create a 0x0 matrix. Logically it does not makes any sense to create a 0x0 matrix, but say in fem problems it is possible in situations that a 0x0 matrix should be created.

Thanks

**Comment by wo80** [comment]
Hey there!
Feeling a bit burned out lately. But maybe that's just the new normal...
How about you?

I agree, if someone wants to create a 0x0 matrix, the code shouldn't prevent from doing so. I'll do a few tests and upload the fix in the next days.

Just out of interest: could you explain where you get the 0x0 matrices?

**Comment by epsi1on** [comment]
Same is with me.
Thanks. I think also stuff like multiplying, factorization etc, also should not throw exception.
I'm getting 0x0 matrix where there is no free DoF in my model.
Also it should be multiplied by a 0x12 matrix!

**Comment by wo80** [comment]
Most of the methods work fine for empty matrices. But what about matrix multiplication? What should the product of a Mx0 with a 0xN be? Algebraically it doesn't make much sense to return a MxN matrix, so I would either throw an exception or return an empty matrix (0x0).

Do you need this kind of matrix multiplication?

**Comment by epsi1on** [comment]
yes, that is ok, Probably i should handle that situation in my code before sending to csparse.
Thanks anyways for great library...
