### ISSUE TITLE
Is CSparse.NET Managed or unmanaged?

### ISSUE THREAD

**Issue by ghost** [wo80/CSparse.NET#12]
Hi, first of all thanks for a great library, you are really saving my thesis =). I was wondering is there some parts of unmanaged code in CSparse or it is a direct translation to C# of Tim Davis`s original code? If there are native code parts, can you describe them a bit more in detail (which part exactly, and is it made in native Fortran C/C++) Thanks again.

**Comment by wo80** [comment]
CSparse.NET is managed code only. If you want to use native solvers from C#, there's a new project https://github.com/wo80/csparse-interop.
