### ISSUE TITLE
Question: AVX vectorization with System.Numerics.Vector<T> possible?

### ISSUE THREAD

**Issue by noname-2** [wo80/CSparse.NET#14]
To start: Awesome project. Would AVX vectorization with System.Numerics.Vector<T> be possible? Is the original CSparse making use of SIMD?

**Comment by wo80** [comment]
The original CSparse code does not make use of SIMD and I have no plans to include support in CSparse.NET using System.Numerics.Vector.

The (static) Vector classes would be natural candidates for SIMD, but those are just helper classes not used internally. So, if anyone feels the need to add some kind of parallelization, those methods can be easily replaced.

Regarding sparse matrix-vector multiplication: from the few articles I read, it seems the efficient use of SIMD largely depends on the storage format, and CSR/CSC are not the optimal choice. I assume, the same holds for anything more complex, like matrix factorization.

**Comment by wo80** [comment]
Closing this one. Feel free to re-open for further discussion.
