### ISSUE TITLE
How to change the value of an already initialized SparseMatrix

### ISSUE THREAD

**Issue by adriaanpfeiffer** [wo80/CSparse.NET#15]
Is it currently foreseen in the library that a value in the SparseMatrix will be changed after first initialization? 
I can see we are able to retrieve the value of sparseMatrix via .At(int i, int j). But I don't see a way to change the value.

The use case is that I need to increase the value of a diagonal cell with a penalty value after some sparsematrix addition and multiplication has taken place.

**Comment by wo80** [comment]
This was intentionally left out because it's very inefficient. If you are seeing a sparse matrix value being set using a `matrix.At(i, j, value)` method, you can be very sure that there's a better way to achieve the same thing.

In your case, go along these lines:
```c#
// Throw exception if diagonal element is missing!
var diag = A.FindDiagonalIndices(true);
var values = A.Values;

var penalty = 0.1;

for (int i = 0; i < A.RowCount; i++)
{
    values[diag[i]] += penalty;
}
```

**Comment by adriaanpfeiffer** [comment]
Ok thanks, suggested approach is sufficient for me.
