### ISSUE TITLE
Cholesky solver

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#16]
Hi,
Thanks for great code. After that i've had problem with a particular matrix and cholesky solver.
For that matrix cholesky solver gave me an array of ```double.NaN```. i am not sure if my matrix was positive definite, but i was expecting that if it is not SPD, then i get an ```matrix should be positive definite``` error. is it true?

Thanks

**Comment by wo80** [comment]
Hey there!

Please check if your input matrix has NaNs. I just tested, and Cholesky (and probably the other factorizations too) does not throw an exception in this case.

If your input matrix has no NaNs, please upload the matrix and I will have a look (use the MatrixMarketWriter, availalable in the latest version of CSparse).

So, in general: should the factorization methods check for NaNs, or should that be left to the user? What do you think?

**Comment by epsi1on** [comment]
> So, in general: should the factorization methods check for NaNs, or should that be left to the user? What do you think?

maybe better to left to user.

**Comment by epsi1on** [comment]
this is the matrix. right hand side have no NaN. this is matrix in matrix market format in zip file:
http://s000.tinyupload.com/index.php?file_id=03650530592839178017

**Comment by wo80** [comment]
Ok, a lot of NaNs in there. So i guess something went wrong when generating the matrix!

**Comment by epsi1on** [comment]
ok, got the problem
