### ISSUE TITLE
Exception when multiplying zero matrices

### ISSUE THREAD

**Issue by andreasg123** [wo80/CSparse.NET#19]
When multiplying two sparse matrices that are all zeros, the following exception occurs:

    Unhandled Exception:
    System.NullReferenceException: Object reference not set to an instance of an object
      at CSparse.Double.SparseMatrix.Multiply (CSparse.Storage.CompressedColumnStorage`1[T] other) [0x000ae] in <441d951ef3a340c28331a195ffb93d84>:0 
      at EmptyMultiply.Main (System.String[] args) [0x0001c] in <265f17d61719442385620412a8f37a5e>:0 
    [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
      at CSparse.Double.SparseMatrix.Multiply (CSparse.Storage.CompressedColumnStorage`1[T] other) [0x000ae] in <441d951ef3a340c28331a195ffb93d84>:0 
      at EmptyMultiply.Main (System.String[] args) [0x0001c] in <265f17d61719442385620412a8f37a5e>:0

This is due to the fact that `Values` isn't allocated for empty matrices: https://github.com/wo80/CSparse.NET/blob/master/CSparse/Storage/CompressedColumnStorage.cs#L57

`result` is an empty matrix if both inputs are empty: https://github.com/wo80/CSparse.NET/blob/master/CSparse/Double/SparseMatrix.cs#L393

However, `Resize` doesn't check if `Values` is `null`: https://github.com/wo80/CSparse.NET/blob/master/CSparse/Storage/CompressedColumnStorage.cs#L762

Sample program:

    using System;
    using CSparse;
    using CSparse.Double;
    
    public class EmptyMultiply
    {
        public static void Main(string[] args)
        {
            var a = SparseMatrix.OfColumnMajor(3, 2, new double[6]);
            var b = SparseMatrix.OfColumnMajor(2, 4, new double[8]);
            a.Multiply(b);
        }
    }

**Comment by wo80** [comment]
Good catch!

I will take a look at it. Not sure why I added the check, I can't think of a good reason right now. The values array should probably be initialized just like the row indices.

**Comment by andreasg123** [comment]
While you look at `NullReferenceException`, you could also look at this: https://github.com/wo80/CSparse.NET/blob/master/CSparse/Double/SparseMatrix.cs#L370

As `other` is used before this check (`int n = other.ColumnCount;`), there would be a `NullReferenceException` earlier.  Also, `SparseMatrix.Add` doesn't have the same test so that it is at least inconsistent.
