### ISSUE TITLE
Let the user configure the degree of parallelism in Parallel.For

### ISSUE THREAD

**Issue by wo80** [wo80/CSparse.NET#22]
The user should be able to configure the degree of parallelism in the parallel matrix multiplication algorithms by passing [ParallelOptions](https://docs.microsoft.com/de-de/dotnet/api/system.threading.tasks.paralleloptions) to the `Parallel.For` calls. This could either be done by adding a method parameter or by adding some configuartion options to the library.

The latter is done in MathNet (see [Control.cs](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Control.cs#L253)) and I'd prefer to do it the same way.

**Comment by andreasg123** [comment]
Offering a means to provide `ParallelOptions` seems to be a good idea. The easiest way would be an optional parameter for `ParallelMultiply`. The MathNet approach for [`CreateParallelOptions`](https://github.com/mathnet/mathnet-numerics/blob/968d0798056a2b4c4cff7091241172466a0e7458/src/Numerics/Threading/CommonParallel.cs#L45) may be a good approach for situations where the optional parameter isn't provided. I wouldn't recommend creating a partitioner as the current approach is tuned for performance.

**Comment by wo80** [comment]
> I wouldn't recommend creating a partitioner as the current approach is tuned for performance.

Yes. Just making the definition of `nblocks` in `ParallelMultiply` not depend on `Environment.ProcessorCount`, but either on a method parameter or `Control.MaxDegreeOfParallelism` (ensuring that this is less or equal `Environment.ProcessorCount` and that the corresponding `ParallelOptions` get passed to `Parallel.For`).
