### ISSUE TITLE
Dual Licensing

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#23]
Hi there.
How can someone use CSparse.NET in a commercial closed source software?
Does it need re-licensing? or pay for new license?
Thanks

**Comment by wo80** [comment]
I'm surely no expert at this, but I think there's no problem using LGPL licensed libraries in commercial software. What you cannot do is copying (parts of) the code directly into your application (at least, if you want to keep it closed source).

More details here: http://answers.google.com/answers/threadview/id/439136.html

**Comment by wo80** [comment]
https://dzone.com/articles/the-lgpl-license

> The LGPL is a weaker form of the GPL that is not contagious over library boundaries. Originally, LGPL was read out as Library General Public License. It has now been reinterpreted to be read out as the Lesser General Public License. I assume they mean lesser, as in less strong in forcing software to be open source.
> 
> Applying LGPL to a library ensures that the library itself and any modified versions of it will remain open source. But it can be used by closed source software.
