### ISSUE TITLE
CoordinatedStorage

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#24]
Hi,
Using CoordinatedStorage like this:

    using Coord = CSparse.Storage.CoordinateStorage<double>;
    var buf = new Coord(10, 10, 0);
    buf.At(2,3,1.0);

will throw exception of `IndexOutOfRangeException`, but this will not:

    using Coord = CSparse.Storage.CoordinateStorage<double>;
    var buf = new Coord(10, 10, 1);
    buf.At(2,3,1.0);

**Comment by wo80** [comment]
Good one!

With the latest commit https://github.com/wo80/CSparse.NET/commit/7f08746b4cbe7777e44e92759e1f60e60c97c176#diff-da791863a395ce110f3e6b55e0cc9fc0L81 I allowed `nzmax` to be zero, but then `Resize(2 * nzmax)` will fail.
