### ISSUE TITLE
L*D*Lt decomposition

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#25]
Hi,
Is there code for L*D*Lt decomposition of symmetric matrices with the library?

**Comment by wo80** [comment]
There's the [SparseLDL](https://github.com/wo80/CSparse.NET/blob/master/CSparse/Double/Factorization/SparseLDL.cs) class, which is a port of SuiteSparses' [LDL](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/LDL/) code. Take a look at the [documentation](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/LDL/Source/ldl.c) there, in particular:

> The routines compute the LDL' factorization of a real sparse symmetric matrix A (or PAP' if a
> permutation P is supplied), and solve upper and lower triangular systems with the resulting L
> and D factors.  If A is positive definite then the factorization will be accurate.  A can be indefinite
> (with negative values on the diagonal D), but in this case no guarantee of accuracy is provided,
> since no numeric pivoting is performed.

I've never used the code. Please let me know if it works for you.

**Comment by epsi1on** [comment]
I did:
- Add [LDL<sup>T</sup> into readme.md file](https://github.com/wo80/CSparse.NET/commit/d202fbdf3e2cfbf2b72d3a92fd2d649361fcaeb0)
- Add [LDL<sup>T</sup> example in wiki](https://github.com/wo80/CSparse.NET/wiki/Sparse-LDLt-example) that needs to be updated (does not have any code yet)

**Comment by epsi1on** [comment]
do you think i should undo my changes?

**Comment by epsi1on** [comment]
> Regarding the quote from the documentation: have you run any tests with indefinite matrices?

No test yet.

**Comment by epsi1on** [comment]
No test yet.
Just for my own information. How can check the accuracy of out results for LDL<sup>T</sup>?
Output of QR or LU can be used?

**Comment by wo80** [comment]
No, it's fine. The wiki example is empty, it should probably be a copy of the Cholesky example. Additionally, there should be a unit test, which can also be copied from the Cholesky test.

Regarding the quote from the documentation: have you run any tests with indefinite matrices?

**Comment by wo80** [comment]
For spd matrices, all factorizations are stable, even without pivoting. LU and QR both implement pivoting. LDL does not, so it's the only factorization included in CSparse.NET which might suffer from numerical instabilities (in case your matrix is indefinite).

To check the accuracy of the factorization, you could do some steps of iterative refinement and test how much the solutions in each step differ. But in general, I wouldn't recommend using code that might suffer from such problems.
