### ISSUE TITLE
CLSCompliant

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#26]
Hello,
For making the CSparse.NET CLSCompliant, these minor changes are needed:

![error](https://user-images.githubusercontent.com/7839141/80108559-adbfc600-8591-11ea-9b44-c82284f9208d.png)

- Convert `Matrix.rowCount` and `Matrix.colCount` accesors from `protected` into `internal`
- Change name of either `Converter.FromDenseArray<T>(T[][] array)` or `FromDenseArray<T>(T[,] array)` in order to have different names.

Do you agree to do these changes? and then from other .net languages like VB.Net, CSparse.NET is accessible

**Comment by wo80** [comment]
Hey there, hope you're doing well!

I don't give too much about VB, but it's probably a good idea to be CLS compliant. I'd rather rename `rowCount`, `columnCount` than changing the visibility. I'll have a look into it.

**Comment by epsi1on** [comment]
Thanks,
This is also required:
- Change name of either Converter.FromDenseArray<T>(T[][] array) or FromDenseArray<T>(T[,] array) in order to have different names.

**Comment by epsi1on** [comment]
Hi,
Any news? Do you need any help on this? just tell me what will you rename `rowCount` and `columnCount` to, i can do it...

**Comment by wo80** [comment]
Sorry for delay, totally forgot about this one :(
