### ISSUE TITLE
Problem with the QR factorization

### ISSUE THREAD

**Issue by krzysztof-michalak** [wo80/CSparse.NET#27]
I tried to use the Francis algorithm to obtain eigenvalues of a sparse matrix, but it always diverged to NaNs. So, I started by checking if the QR factorization works correctly. I used the following code:

[Program.zip](https://github.com/wo80/CSparse.NET/files/4673190/Program.zip)

The results seem to be wrong, because the bottom-right element in R seems to be negated compared to results in Octave, and, most importantly, multiplying Q * R does not give A:

A:
7 2
2 1

Q:
14.2801098892805 0
2 0.824163383692134

R:
-7.28010988928052 -2.19776902317902
0 -0.412081691846067

Q * R:
-103.960769224964 -31.3843831622532
-14.560219778561 -4.73516068786748

Octave code and results for comparison:

>> A = [ 7 2; 2 1 ]

A =

   7   2
   2   1

>> [Q, R] = qr(A)

Q =

  -0.96152  -0.27472
  -0.27472   0.96152

R =

  -7.28011  -2.19777
   0.00000   0.41208

>> Q * R

ans =

   7.0000   2.0000
   2.0000   1.0000

**Comment by wo80** [comment]
The Q of `SparseQR` is not the actual Q matrix, but it stores the Householder vectors. Take a look at the `ApplyHouseholder` method at [SparseQR.cs#L172](https://github.com/wo80/CSparse.NET/blob/947967d2652703e8da7d622bbd17febecf29a98b/CSparse/Double/Factorization/SparseQR.cs#L172). You will also have to take the `beta` array into account for your computation.

**Comment by wo80** [comment]
As already mentioned [here](https://github.com/wo80/CSparse.NET/issues/13#issuecomment-628786870), the whole procedure of explicitly computing Q will be very inefficient!

**Comment by wo80** [comment]
BTW: Francis algorithm isn't meant for sparse matrices, it usually produces complete fill-in. Though the QR method is part of sparse eigenvalue algorithms like Lanczos or Arnoldi, it operates only on a small part of the spectrum (since usually only a few eigenvalues are requested).

**Comment by wo80** [comment]
So here's a quick test I did, showing the sparsity of the involved matrices and the time to compute the factorization and to compute the actual Q:
```
// Column ordering: natural
N =  100: A  4.6% , H 10.1% , R 18.3% , Q 59.6%, fac time:   0ms, Q time:    12ms
N =  200: A  2.4% , H  7.2% , R 13.4% , Q 56.9%, fac time:   1ms, Q time:    78ms
N =  400: A  1.2% , H  5.0% , R  9.5% , Q 54.9%, fac time:   2ms, Q time:   662ms
N =  800: A  0.6% , H  3.6% , R  6.9% , Q 53.5%, fac time:   8ms, Q time:  4962ms
N = 1600: A  0.3% , H  2.5% , R  4.9% , Q 52.5%, fac time:  28ms, Q time: 43323ms

// Column ordering: minimum degree A'A
N =  100: A  4.6% , H  8.4% , R 14.2% , Q 37.4%, fac time:   0ms, Q time:     8ms
N =  200: A  2.4% , H  5.6% , R  9.7% , Q 29.6%, fac time:   1ms, Q time:    40ms
N =  400: A  1.2% , H  3.5% , R  6.2% , Q 21.7%, fac time:   2ms, Q time:   238ms
N =  800: A  0.6% , H  2.2% , R  3.9% , Q 17.8%, fac time:   5ms, Q time:  1579ms
N = 1600: A  0.3% , H  1.3% , R  2.4% , Q 12.8%, fac time:  15ms, Q time: 10655ms
```
**Edit**: the matrix A is the standard 2d Laplacian
