### ISSUE TITLE
Can I create a sparse matrix by a list of triples?

### ISSUE THREAD

**Issue by AlbertLiDesign** [wo80/CSparse.NET#30]
I have created a list of triplets. But I don’t know if I can convert them into a CSparse matrix. Besides, I very like your work but where can I get some documentation or tutorials?

**Comment by wo80** [comment]
How are your triplets stored? I recommend using the `CoordinateStorage` class that comes with CSparse.NET:
```c#
// CoordinateStorage = triplet storage
var coo = new CoordinateStorage<double>(rows, columns, nnz);

// Fill storage using:
coo.At(i, j, value);

// Convert to sparse matrix (CSC storage).
var A = SparseMatrix.OfIndexed(coo);
```
Alternatively, there's `SparseMatrix.OfIndexed(rows, columns, enumerable)` which takes an `IEnumerable<Tuple<int, int, double>>` enumerable.

There's no documentation besides the inline xml doc (which is pretty complete). Some examples are in the [wiki](https://github.com/wo80/CSparse.NET/wiki). Maybe a simple _Getting started_ example could be added...

**Comment by AlbertLiDesign** [comment]
Thank you!

**Comment by AlbertLiDesign** [comment]
Thank you for your amazing work. Merry Christmas 😁

**Comment by wo80** [comment]
Thanks, I wish you merry christmas too!
