### ISSUE TITLE
[Question] Adding two sparse matrices

### ISSUE THREAD

**Issue by SaMohamed** [wo80/CSparse.NET#32]
Greetings,

why adding a matrix B to an existing matrix A requires matrix C,
I think the default behavior should be adding B to A and return A itself.

```
 /// <summary> 
 /// Adds two matrices, A = alpha*A + beta*B, where A is current instance. 
 /// </summary> 
public abstract void Add(T alpha, T beta, CompressedColumnStorage<T> other); 
```

https://github.com/wo80/CSparse.NET/blob/1f1357a619f11bbb628a2c5f8190e0388beb47cf/CSparse/Storage/CompressedColumnStorage.cs#L406-L419

**Comment by wo80** [comment]
I'm not sure if it's worth adding a separate method for this. You are probably thinking of saving memory allocations, but for this to work, the matrix `A` would have to provide enough space to hold the non-zeros of `A+B`, which you cannot take for granted. Usually, sparse matrices will provide only enough memory to hold their own non-zeros, so the proposed method would only work if `A + B` has the same number of non-zeros as `A`.

**Comment by epsi1on** [comment]
if both `A` and `B` have same nonzero pattern, then simply you can make an extension method that adds `B.Values` to `A.Values` which have same length.

**Comment by SaMohamed** [comment]
The idea here is that i'm driving a stiffness matrix using Gauss Legendre Rule. 
and in each weight, i'll add matrix Bt*B to matrix K.
![image](https://user-images.githubusercontent.com/21183259/107616288-702e4580-6c56-11eb-8eaa-761c6ffc945e.png)


> if both `A` and `B` have same nonzero pattern, then simply you can make an extension method that adds `B.Values` to `A.Values` which have same length.

and i'm not sure about that.

**Comment by wo80** [comment]
For your local element integration use `DenseMatrix`. Assemble those into the global stiffness matrix using the `CoordinateStorage<double>` class, mapping the local indices of the dense matrix to global indices. When you're done assembling, convert the coordinate storage using `SparseMatrix.OfIndexed(coo)`.

**Comment by wo80** [comment]
Btw, the procedure I described above is the easiest way to approach assembling. A different approach is computing the non-zero pattern of the final stiffness matrix first and then start assembling. In this case, using an `Add` method like you suggested would make sense.

**Comment by epsi1on** [comment]
> 
> 
> The idea here is that i'm driving a stiffness matrix using Gauss Legendre Rule.
> and in each weight, i'll add matrix Bt*B to matrix K.
> ![image](https://user-images.githubusercontent.com/21183259/107616288-702e4580-6c56-11eb-8eaa-761c6ffc945e.png)
> 
> > if both `A` and `B` have same nonzero pattern, then simply you can make an extension method that adds `B.Values` to `A.Values` which have same length.
> 
> and i'm not sure about that.

As @wo80 said, it think better to use `DenseMatrix` too, specially for this purpose (element's stiffness matrix) ...
How much is maximum possible dimension of K matrix? You should use sparse matrix only when nonzero memers are less than say 10% of whole matrix, otherwise you will decrease the performance and better to use `DenseMatrix`...

**Comment by epsi1on** [comment]
I suggest this pseudo code with object oriented approach to deal with this issue (by pseudo I mean maybe methods or members are not spelled correctly, code is not compilable  )

```
var kCoord=new CoordinateStorage(n,n,1);//n is total DoFs

foreach(var element in Elements)
{
   var k = element.GetGlobalStiffnessMatrix();//element's global stifness matrix with say 12x12 size
   for(var i=0;i<k.RowCount;i++)
      for(var j=0;j<k.ColumnCount;j++)
      {
         var iCoord=some computation ... ;//the global # of dof related to i'th dof of k matrix
         var jCoord=some computation ... ;//the global # of dof related to j'th dof of k matrix

         kCoord.At(iCoord,jCoord,k[i,j];
      }
}

var kGlobal=kCoord.ToSparse();//convert coordinated storage to sparse matrix
```

Also note the CoordinateStorage is specially usable in your case...

**Comment by SaMohamed** [comment]
Thank you all for your support and explanation, I will close this for now.
