### ISSUE TITLE
A bug when converting a COO matrix into CSC matrix

### ISSUE THREAD

**Issue by AlbertLiDesign** [wo80/CSparse.NET#35]
When I create a coo matrix using pre-defined arrays, the created coo matrix doesn't have the number of non-zeros. Therefore, when I convert the COO matrix into a CSC matrix, all values are lost. Because the converting code will check the number of non-zeros. If the number of non-zeros is 0, the converting would be failed.

For example, ik, jk, sk are pre-defined arrays. The created COO matrix doesn't have the number of non-zeros. Then, matrix A has no any values.
``` C#
        var coo = new CoordinateStorage<double>(2 * (nelx + 1) * (nely + 1), 2 * (nelx + 1) * (nely + 1), ik, jk, sK);

        var A = (SparseMatrix)SparseMatrix.OfIndexed(coo);
```

**Comment by wo80** [comment]
Ok, I'll add another constructor that takes the non-zero count, like
```c#
        /// <summary>
        /// Initializes a new instance of the <see cref="CoordinateStorage{T}"/> class.
        /// </summary>
        /// <param name="rowCount">The number of rows.</param>
        /// <param name="columnCount">The number of columns.</param>
        /// <param name="nonZerosCount">The number of non-zeros in the given arrays.</param>
        /// <param name="rowind">The row indices array.</param>
        /// <param name="colind">The column indices array.</param>
        /// <param name="values">The values array.</param>
        public CoordinateStorage(int rowCount, int columnCount, int nonZerosCount, int[] rowind, int[] colind, T[] values)
```

This should solve your problem right?

**Comment by AlbertLiDesign** [comment]
> Ok, I'll add another constructor that takes the non-zero count, like
> 
> ```cs
>         /// <summary>
>         /// Initializes a new instance of the <see cref="CoordinateStorage{T}"/> class.
>         /// </summary>
>         /// <param name="rowCount">The number of rows.</param>
>         /// <param name="columnCount">The number of columns.</param>
>         /// <param name="nonZerosCount">The number of non-zeros in the given arrays.</param>
>         /// <param name="rowind">The row indices array.</param>
>         /// <param name="colind">The column indices array.</param>
>         /// <param name="values">The values array.</param>
>         public CoordinateStorage(int rowCount, int columnCount, int nonZerosCount, int[] rowind, int[] colind, T[] values)
> ```
> 
> This should solve your problem right?

Yes, I think it will work!

**Comment by wo80** [comment]
@AlbertLiDesign I will publish new package later today.

I'm planning to remove the `net45` target assembly, keep `netstandard2.0` and upgrade `net5.0` to `net6.0`. Would this break anything for you?

**Comment by AlbertLiDesign** [comment]
> @AlbertLiDesign I will publish new package later today.
> 
> I'm planning to remove the `net45` target assembly, keep `netstandard2.0` and upgrade `net5.0` to `net6.0`. Would this break anything for you?

Thank you for your message.

I think it doesn't affect my program.
