### ISSUE TITLE
Can I slice a CSC sparse matrix?

### ISSUE THREAD

**Issue by AlbertLiDesign** [wo80/CSparse.NET#36]
Hello,

I'm writing a Finite element framework. And I need to remove several rows and columns from a CSC sparse matrix `A`. In Matlab, I can use slicing operations like `A([2,  3, 4], [6, 7, 8])` to select several rows and columns for computing. How can I implement this using CSparse? 

Or can I access a value from the CSC sparse matrix by inputting `(i, j)`?

Cheers

**Comment by epsi1on** [comment]
Hi,
Not sure if directly possible to slice a sparse matrix, but an option would be to use permutation matrix to slice it. Check this stackoverflow.com question which is probably near to what you need:
 [StackOverflow.com: Solving a linear system of equations](https://stackoverflow.com/a/54839612/1106889)

**Comment by AlbertLiDesign** [comment]
> Hi, Not sure if directly possible to slice a sparse matrix, but an option would be to use permutation matrix to slice it. Check this stackoverflow.com question which is probably near to what you need: [StackOverflow.com: Solving a linear system of equations](https://stackoverflow.com/a/54839612/1106889)

Hi,

This is a good idea. I expect CSparse to implement this feature. 

Have a nice day!

**Comment by wo80** [comment]
I've added a simple row/column extraction method to the [csparse-extensions](https://github.com/wo80/csparse-extensions/) project:
[CompressedColumnStorageExtensions.cs#L74-L82](https://github.com/wo80/csparse-extensions/blob/master/CSparse.Extensions/Storage/CompressedColumnStorageExtensions.cs#L74-L82)

See the tests for usage:
[CompressedColumnStorageTests.cs#L54-L74](https://github.com/wo80/csparse-extensions/blob/master/CSparse.Extensions.Tests/Storage/CompressedColumnStorageTests.cs#L54-L74)

**Comment by AlbertLiDesign** [comment]
> I've added a simple row/column extraction method to the [csparse-extensions](https://github.com/wo80/csparse-extensions/) project: [CompressedColumnStorageExtensions.cs#L74-L82](https://github.com/wo80/csparse-extensions/blob/master/CSparse.Extensions/Storage/CompressedColumnStorageExtensions.cs#L74-L82)
> 
> See the tests for usage: [CompressedColumnStorageTests.cs#L54-L74](https://github.com/wo80/csparse-extensions/blob/master/CSparse.Extensions.Tests/Storage/CompressedColumnStorageTests.cs#L54-L74)

Thank you for your amazing work!
