### ISSUE TITLE
Nuget .net version compatibility

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#39]
Hi
The lowest .NET version that is supported by the csparse [nuget package](https://www.nuget.org/packages/CSparse/#supportedframeworks-body-tab) is net 4.6.1 by now. Is it possible to also include older ones, like net45 or even fossile ones like net40?

Thanks

**Comment by wo80** [comment]
Official Microsoft support of .NET Framework versions <= 4.6.1 ended in April 2022. I currently don't even have the net45 framework target installed in Visual Studio and I'd like to keep it that way.

**Comment by epsi1on** [comment]
So I think i should use nuget package version 3.5.0 for net45, or 3.4.9 for net40 support.
Thanks anyways...
