### ISSUE TITLE
Adding Span and Memory

### ISSUE THREAD

**Issue by delicioustuna** [wo80/CSparse.NET#41]
Hello! Thank you sincerely for providing a nice sparse matrix library.

I would like to apply Span<T> and Memory<T> to function arguments provided by CSparse.NET.
For example, SparseCholesky.Solve(ReadOnlySpan<double> input, Span<double> result) for SparseCholesky.Solve(double[] input, double[] result) Is it possible to add an overload on the CSparse.NET side so that I can do this?

**Comment by wo80** [comment]
> Hello! Thank you sincerely for providing a nice sparse matrix library.

Hello @delicioustuna , thanks for your kind words!

Adding `Span` support to the `Solve` methods shouldn't be difficult. Would you like to go ahead and create a pull request?

**Comment by delicioustuna** [comment]
Thank you for your prompt response.
I have created a pull request.

https://github.com/wo80/CSparse.NET/pull/42

I need to add a reference to System.Memory.dll, is this an acceptable change?

**Comment by wo80** [comment]
> I need to add a reference to System.Memory.dll, is this an acceptable change?

Yes, that's ok for now. Though I like a "zero dependencies" approach, this is much cleaner than having `#if NETCOREAPP2_1_OR_GREATER` all across the code. I might change that later on, in case I get any complaints.

But please add the dependency only where necessary, so
```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
  <PackageReference Include="System.Memory" Version="4.5.5" />
</ItemGroup>
```

**Comment by delicioustuna** [comment]
Thank you for your reply and for pointing out the additional dependency.

I too would prefer a format with zero dependencies whenever possible, and since there was no better alternative for Span<T> than to refer to Sytem.Memory.dll, this is the way to do it. I hope this will not be a problem for other users.

I will make the changes you suggested. Please wait a moment.
