### ISSUE TITLE
Publish symbols and source for debugging

### ISSUE THREAD

**Issue by ChristoWolf** [wo80/CSparse.NET#45]
Hi!

## Feature request

Would be great for debugging if you published those data with your NuGet package as described [here](https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/debugging-with-symbols-and-sources.md).

Without these, I was not able to generate any usable debugging information even when decompiling.

**Comment by wo80** [comment]
Good idea! I'll publish a [snupkg](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) package with the 4.0.0 release (in the next days). I think that should work even without source link. In case it doesn't work, I'll add source link in a patch release.

**Comment by ChristoWolf** [comment]
Sounds great, thanks!

**Comment by wo80** [comment]
Alright, version 4 with symbol package is online. I tested it and debugging works. You need to check the following Visual Studio options:
1) Debugging > General
   * Disable "Enable Just My Code"
2) Debugging > Symbols
   * Enable "Nuget.org Symbol Server"
   * Optionally, enable "Load only specified modules" and add "CSparse.dll"
 
In case you want to use vscode, check https://code.visualstudio.com/docs/csharp/debugging#_user-settings

Please let me know if this works for you!

**Comment by ChristoWolf** [comment]
Works perfectly, thanks a ton @wo80!
