### ISSUE TITLE
[Feature request] Add Matrix Inverse

### ISSUE THREAD

**Issue by xahu** [wo80/CSparse.NET#5]

**Comment by epsi1on** [comment]
I think the inverse of a sparse matrix can be a dense matrix, so you maybe need to convert your sparse matrix to a dense matrix and then use a dense matrix library (like Math.NET) for inverting.

**Comment by wo80** [comment]
This will not be part of CSparse.NET and as @epsi1on pointed out, computing the inverse of a sparse matrix isn't a good idea. If you need to compute the inverse explicitly, use one of the factorizations, for example `SparseLU`, see [wiki](https://github.com/wo80/CSparse.NET/wiki/Inverse-matrix).

**Comment by xahu** [comment]
:thumbsup:
