### ISSUE TITLE
A very specific form of matrix!

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#50]
Hi,
If $A_{m.n}$ is a rectangular `m*n` matrix where `n>m` and rank of $$A$$ is `m`.
With help of elementary operation of rows (Gaussian elimination), I need to convert this matrix to a form that there be `m` columns, each column only have exactly one nonzero member which value equals `1.0`. 
Then i can easily permute rows and columns of this matrix into this form:

$$B_{m.n}=\begin{bmatrix}
 I_{m*m} & R_{(n-m)*n} 
\end{bmatrix} $$

where:
- $$I_{m*m}$$: is identity matrix with size $m$, 
- $$R_{(n-m)*n}$$: is a matrix with unknown nonzero pattern.

$$R$$ sub matrix is likely a dense matrix and not a sparse matrix, but in my application it is sparse, of course if fill reduce methods used.
My target is to find $$R$$ submatrix having $$A$$ as input.
I was hoping there is a ready decomposition (already in this library) which i can use for the first part (Gaussian elimination),
My challenge is part one (Gaussing elimination), second part (permutation) do not have any challenges.
Thank you

**Comment by epsi1on** [comment]
let me reorder my question.
I need to make matrix A into a form that, in each row there be a nonzero element which it is only nonzero in it's column.

Thanks

**Comment by wo80** [comment]
Hi @epsi1on 

> I was hoping there is a ready decomposition (already in this library) which i can use for the first part (Gaussian elimination)

The CSparse LU decomposition only supports square matrices unfortunately. May I ask what you are ultimately trying to achieve? If you were trying to solve a linear system, I'd suggest the QR decomposition, but I guess that's not what you are up to...

**Comment by epsi1on** [comment]
Thanks for reply.

> May I ask what you are ultimately trying to achieve? If you were trying to solve a linear system, I'd suggest the QR decomposition, but I guess that's not what you are up to...
Actually i'm trying to inject some extra equations into main eq system.

In simple terms, i'm trying to find a method to inject some extra equations into a sparse eq system and reduce the number of unknowns.
In finite element solve procedure, when i assemble the full stiffness matrix with help of `CoordinateStorage<double>` class , the result is a sparse matrix with size `n*n`. Lets call it `K` matrix. This matrix is singular, thus irreversible and incompatible with Cholesky factorization. If one try to factorize this matrix, will get exception with message `Matrix must be positive definite`.

There are boundary conditions, defined in FEM model which should be applied to the system. Usually some DoFs in the model are bound to ground, so that they will not move and the value of them are known. for example $$\Delta_1=0$$. In the FE model, there are `m` boundary conditions. `m` DoFs are bound to ground.
A very usual method for applying simple boundary conditions, is to remove appropriated row and column from original system. but it only works for simple boundary conditions, like $$\Delta_i=0$$. but for applying a more complicated equation like $$3.\Delta_1+4*\Delta_2=-2$$ into main system, there is need for another method which i'm trying to describe it with math language. and i'm in a situation that need to reduce the boundary condition system into a the special form which i described above.
in #7 i asked some help and it did worked, really great solution and practically have no numerical errors. The problem is it is not in math language, thus i cannot proof it with math. also speed have much room to improve. Applying boundary conditions with that method takes about 10% of Cholesky decomposition, and same amount of time with CG algorithm.
Sorry for long text and thanks for your attention.

**Comment by epsi1on** [comment]
Also if you know a better way to inject extra equations into original eq system, please tell me.
The sparse qr speed is very good, in method proposed in #7, for a specific examples qr decomposition takes 5ms, but about 700ms took for rest of stuff. i hope to reduce this 700ms to somewhere around 100ms or less by optimizing the method which i believe have room to optimize even for less than 100ms

**Comment by epsi1on** [comment]
Also please note that nonzero count of the boundary condition eq system is extremely small. 
Total number of nonzero members are usually $$^3\sqrt{n}$$ where $$n$$ is original matrix row/column count.
In some case can be like $$n$$ or more.

**Comment by wo80** [comment]
It's hard to give an advice without having the full picture. It's clear how to apply Dirichlet boundary conditions - without those conditions the problem is ill-posed, which is reflected by the system matrix being singular. It's not clear to me what boundary conditions give rise to your extra equations. How does the system given by those extra equations actually look like? What is the number of equations, the number of unknowns, the expected rank? Would it be possible to solve this system alone and then use the solution to provide the constraints to the original system matrix as done with Dirichlet boundary conditions?

**Comment by epsi1on** [comment]
Many thanks for the reply.
Pls let me show you with an example.

Please consider this equation system, which is related to a FE model:

$$\begin{bmatrix}
f_0 \\ 
f_1 \\ 
f_2 \\ 
f_3
\end{bmatrix} =
\begin{bmatrix}
+1&-1&0&0\\
-1&+1&0&0\\
0&0&+1&-1\\
0&0&-1&+1\\
\end{bmatrix}.
\begin{bmatrix}
\delta_0 \\
 \delta_1\\
 \delta_2\\
 \delta_3
\end{bmatrix}$$

Simplified as:
$$\vec{F}=\hat{K}.\vec{\Delta}$$ 

Think of:
- All members of $$\vec{F}$$ and $$\vec{\Delta}$$ are unknown to us (4+4=8 unknowns)
- All members of $$\hat{K}$$ are known to us.

There are 4 of additional equations, which is extracted from FE model ( i call it boundary conditions):

- $$\delta_0=1.0$$
- $$\delta_1=\delta_2$$
- $$f_1=f_2$$
- $$f_3=5.0$$



Or in matrix form:

$$\begin{bmatrix}
0&0&0&0\\
0&0&0&0\\
0&+1&-1&0\\
0&0&0&+1\\
\end{bmatrix}.\begin{bmatrix}
f_0\\
f_1\\
f_2\\
f_3
\end{bmatrix} +
\begin{bmatrix}
+1&0&0&0\\
0&+1&-1&0\\
0&0&0&0\\
0&0&0&0\\
\end{bmatrix}.
\begin{bmatrix}
\delta_0\\
\delta_1\\
\delta_2\\
\delta_3
\end{bmatrix}=
\begin{bmatrix}
1.0\\
0.0\\
0.0\\
5.0
\end{bmatrix}$$

or simplified:

$$\hat{l}.\vec{F}+\hat{p}.\vec{\Delta}=\vec{r}$$

> Please note: No $$f_i$$ and $$\delta_j$$ will appear in same equation. That is, each row which have a nonzero in $$\hat{l}$$ have only zero members in the $$\hat{p}$$ and vice versa.

> Please note: that all members of $$\hat{l}$$ and $$\hat{p}$$ and $$\vec{r}$$ are known to us.

Until here we have 8 unknown, and 8 equations (4 from original eq system and 4 from boundary conditions). 
Seems all unknowns could be found, but not easy. I was using some tricks to overcome to this. If you think it helps, i can give some information about current method i'm using ([LINK](https://bfenet.readthedocs.io/en/latest/miscellaneoustopics/solveprocedure.html#applying-boundary-conditions-and-mpc-elements-new-method)) which i form some $$P$$ matrix and pre and post multiply to main eq system which reduce the overal size of $$K$$ matrix and i can factorize it with Cholesky method. here is where i need your advice. is there any simple way to boundary conditions into main eq system?

Thanks

**Comment by wo80** [comment]
I probably still don't get it :)

The example of two systems of equations you have written out above can simply be combined to the following matrix, which can be solved with LU. What am I missing?

$$\begin{bmatrix}
1 & 0 & 0 & 0 & -1 & 1 & 0 & 0 \\
0 & 1 & 0 & 0 & 1 & -1 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 & -1 & 1 \\
0 & 0 & 0 & 1 & 0 & 0 & 1 & -1 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & -1 & 0 \\
0 & 1 & -1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0
\end{bmatrix} .
\begin{bmatrix}
f_0 \\
f_1 \\
f_2 \\
f_3 \\
\delta_0 \\
\delta_1 \\
\delta_2 \\
\delta_3
\end{bmatrix} =\begin{bmatrix}
0 \\
0 \\
0 \\
0 \\
1 \\
0 \\
0 \\
5 \\
\end{bmatrix}$$

**Comment by epsi1on** [comment]
>What am I missing?

Actually you are right. I have not looked from this view :)
I think the problem is the speed. i currently use a method which can converts this problem into a 2x2 Cholesky factorization and a bunch of multiplies.

Not sure, but I think difference will be more obvious when a model with 200k size (200k by 200k ) is being factorized with LU vs (100k by 100k) with Cholesky. not sure about the effect of nonzero pattern on LU.

What do you think about the speed?

Thanks

**Comment by wo80** [comment]
> What do you think about the speed?

Reducing size and using Cholesky will always bring a significant speedup!

I'm slowly getting a clearer picture here, so we can go on with the discussion. Let's stick to your example above:

I can see how you can easily eliminate $\delta_0, f_3$. You can also eliminate two of $\delta_1, f_1,\delta_2, f_2$, but one question is, how this can be done in general in a reliable way, right? Or have you already written this code after our discussion in #7 ?

Another question for me: will those boundary conditions always look symmetric? How would you expect to end up with a symmetric system after reduction?

**Comment by wo80** [comment]
> > What do you think about the speed?
> 
> Reducing size and using Cholesky will always bring a significant speedup!

I'm also wondering:

Consider the approach I mentioned [above](https://github.com/wo80/CSparse.NET/issues/50#issuecomment-2329092550) (combining the extra equations with the system matrix and then solving with LU). A fair comparison of the running time with your approach would include:
* converting the extra equations system to RREF (comparable to doing the LU of the smaller system)
* eliminating equations from the main system with help of RREF
* solving reduced system with Cholesky (in case the matrix is symmetric pos def, otherwise LU)

So after all, it's not clear if this will be a lot faster than just doing the LU of the combined system (but it's still possible, you probably have a better insight on how those systems look like).

**Comment by epsi1on** [comment]
> > > What do you think about the speed?
> > 
> > 
> > Reducing size and using Cholesky will always bring a significant speedup!
> 
> I'm also wondering:
> 
> Consider the approach I mentioned [above](https://github.com/wo80/CSparse.NET/issues/50#issuecomment-2329092550) (combining the extra equations with the system matrix and then solving with LU). A fair comparison of the running time with your approach would include:
> 
>     * converting the extra equations system to RREF (comparable to doing the LU of the smaller system)
> 
>     * eliminating equations from the main system with help of RREF
> 
>     * solving reduced system with Cholesky (in case the matrix is symmetric pos def, otherwise LU)
> 
> 
> So after all, it's not clear if this will be a lot faster than just doing the LU of the combined system (but it's still possible, you probably have a better insight on how those systems look like).


The thing is that usually $$\hat{l}$$ and $$\hat{p}$$ are in RREF format originally, or just need a simple permutation to be in RREF.
After all, as you said maybe there be no performance difference with LU of a `n*n` sparse matrix with say 5%nnz (nnz count equal to $$0.05\*n^2$$) , and LU of another sparse matrix with size `2n*2n` with nnz count of $$0.05*n^2+n$$).  $$\hat{l}$$ and $$\hat{p}$$ are extremely sparse, total nnz count can be from $$^3\sqrt{n}$$ to $n$.

Do the Cholesky and LU on same system have significant difference (both speed and memory usage)?

**Comment by epsi1on** [comment]
> Another question for me: will those boundary conditions always look symmetric? How would you expect to end up with a symmetric system after reduction?

I believe so, which is the system after row reduction will be symmetric pos def. because of i do not implement those elements which do convert the system into asymmetric :)

**Comment by wo80** [comment]
> Do the Cholesky and LU on same system have significant difference (both speed and memory usage)?

Cholesky will always outperform LU significantly, both in CPU (see [csparse-interop Tests](https://github.com/wo80/csparse-interop/wiki/Test-Results)) and memory usage.

Regardless of whether the final system should be solved by Cholesky or LU, lets summarize what we have so far with respect to your approach:

* We have the main system assembled as a `SparseMatrix`
* We have some extra equations given by boundary conditions, also stored as a `SparseMatrix`?
* Those extra equations are basically in RREF, up to permutations. Row permutations won't play a role in the elimination step, column permutations would have to be taken care of!

Your initial question was, whether CSparse provides some code which does the elimination, right? That is, eliminating unknowns from the main system using the boundary conditions in RREF? CSparse.NET does not provide the code for this, but it shouldn't be hard to implement. Do you need any help there or do you already have the code ready?

**Comment by epsi1on** [comment]
Hi, thank you for the reply.

> We have the main system assembled as a `SparseMatrix`

This is true.
> We have some extra equations given by boundary conditions, also stored as a `SparseMatrix`?

This is true.
> Those extra equations are basically in RREF, up to permutations. Row permutations won't play a role in the elimination step, column permutations would have to be taken care of!

Not completely true. Say 95% of times, this statement is true. but in 5% there is need for few row eliminations to convert $\hat{l}$ and $\hat{p}$ to RREF. By terms `few row eliminations` i mean something like `n` eliminations. 

> Your initial question was, whether CSparse provides some code which does the elimination, right? 

yes, am still seeking for a way to convert `l` and `p` to RREF format or to a format which is a single permutation away from being RREF. I think i've found a proper and general method to inject these extra equations into main eq system which i'm working on. but need them in RREF format.

> That is, eliminating unknowns from the main system using the boundary conditions in RREF?

yes, i still think that i need both $\hat{l}$ and $\hat{p}$ in the RREF format, or in a special format (as stated in the issue title), which after a single permutation it convert to RREF.

> CSparse.NET does not provide the code for this, but it shouldn't be hard to implement. Do you need any help there or do you already have the code ready?

I think I'll need your help.

Thanks

**Comment by epsi1on** [comment]
I just thinking that i can use QR instead of RREF. Need some time and effort. i'll come back to you later.

**Comment by epsi1on** [comment]
After some effort i end up with this:

submatrices of $\hat{l}$ (total size `n.n`):

$$\hat{l_{n.n}}  =
\begin{bmatrix}
t_{1(m.m)} & t_{2(m.(n-m))} \\
0_{(n-m).(m)} & 0_{(n-m).(n-m)} \\
\end{bmatrix}$$



I ended up needing result of $t_1^{-1}*t_2$ as a sparse matrix (it is not multiplied with a vector on the right side, so factorization cannot be directly used).


due to [RREF page in Wikipedia](https://en.wikipedia.org/wiki/Row_echelon_form) 

> Given a matrix in reduced row echelon form, if one permutes the columns in order to have the leading 1 of the ith row in the ith column, one gets a matrix of the form

> $$\begin{pmatrix}I&X\\
0&0\end{pmatrix}$$

based on wikipedia page, if $\hat{l}$ is in RREF format, then $t_1$ could be converted to identity matrix with some permutation and it will fix the issue $t_1^{-1}*t_2=I^{-1}*t_2=t_2$

$\hat{l}$ is extremely sparse, thus factorized with qr very fast. please have a look at next comment.

**Comment by epsi1on** [comment]
we have arbitrary matrix $\hat{L}$ with known entries.
- size: `mxn` matrix with `m` rows. 
- ~~ss$Rank(\hat{L}) =m$~~
-  $Rank(\hat{L}) =w$ (w is not known, should be detected)
- m < n
- consist of two sub matrices:

```math
\hat{L} = \begin{bmatrix} t_1 & t_2 \end{bmatrix}
```

- $t_1$ is `m.m` and t2 is `(m).(n-m)` in size

Regarding $\hat{L}$, since `row count` < `column count`, the QR will factorize the transpose of $\hat{L}$:

$QR(\hat{L}^T)=Q_{n.m}.R_{m.m}$

Which means:

$$\hat{L}^T=
\begin{bmatrix}
t_1^T \\
t_2^T
\end{bmatrix}=Q.R$$

Split $Q$:

```math
Q_{n.m}=\begin{bmatrix}a_{(m).(m)} \\ b_{(n-m).(m)} \end{bmatrix}
```
```math
\hat{L}^T=\begin{bmatrix}t_1^T\\t_2^T\end{bmatrix}=
\begin{bmatrix}a.R\\b.R\end{bmatrix}
```

So:

$t_1=R^T.a^T$ 
$t_2=R^T.b^T$

And : 
$t_1^{-1}=a^{-T}.R^{-T}$

I need to find result of $(t_1^{-1}.t_2)$ and i think it is sparse, which is $a^{-T}.R^{-T}.R^{T}.b^{T}=(b.a^{-1})^T$

If i can assume $a^{-1}=a^T$ due to orthogonality then solution simplified to:

$t_1^{-1}.t_2=(b.a^{T})^T=a.b^T$

which i'm almost sure my assumption is not true. do you have any idea? except finding $t_1^{-1}$ column by column? (because i think it will take time in execution)

Thank you.

**Comment by wo80** [comment]
> If i can assume $a^{-1}=a^T$ due to orthogonality

But that's not true in general. If $Q_{(n.m)}$, $n > m$ has columns which are pairwise orthogonal, you cannot expect the $m \times m$ submatrix $a_{(m, m)}$ to be orthogonal.

**Comment by epsi1on** [comment]
> But that's not true in general. If Q ( n . m ) , n > m has columns which are pairwise orthogonal, you cannot expect the m × m submatrix a ( m , m ) to be orthogonal.

Thanks for reply.
Do you think there is any neat way to compute  $(t_1^{−1} . t_2 )$ without computing $t_1^{−1}$ column by column?

**Comment by epsi1on** [comment]
> but it shouldn't be hard to implement. 

Could you please give me some initial points on where to start?
Thank you

**Comment by wo80** [comment]
So $\hat{L} = [\ t_1 \ \ t_2\ ]$ is $m \times n$, $m < n$ with rank $m$. The main problem is, that we don't know whether $t_1$ has rank $m$, so there is no such thing like $t_1^{-1}$, right? That's why you want to use QR to factorize the complete $\hat{L}$.

I tried QR on some example matrices with above properties to find the linear independent columns by examining the permutations in `pinv`. Without success unfortunately. I feel that all this is getting quite messy and CSparse might just not be the right tool for this.
Since the system established by the boundary conditions seems to be rather small, have you considered using dense RREF implementations?

**Comment by epsi1on** [comment]
> So L ^ = [   t 1     t 2   ] is m × n , m < n with rank m . The main problem is, that we don't know whether t 1 has rank m , so there is no such thing like t 1 − 1 , right? That's why you want to use QR to factorize the complete L ^ .

Actually situation is a little more complicated than what you described. Aside duplicated equations, There could be incompatible equations which i should detect and throw an exception for user to know that something went wrong. by incompatible equations, i mean a system like this:
- $\delta_1=\delta_2$
- $\delta_1=0.0$
- $\delta_2=1.0$

I think question is changed to:
- input matrix $\hat{L}$ size is `m.n` with rank `w` which is unknown.

> Since the system established by the boundary conditions seems to be rather small, have you considered using dense RREF implementations?

Yea. usually boundary conditions could broke into independent tiny parts so treating as dense matrix would be helpful.

**Comment by epsi1on** [comment]
Thanks for the information.

**Comment by epsi1on** [comment]
I'll probably come back >:)
