### ISSUE TITLE
Q(R) orthogonality

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#51]
Hi,
When i use QR for a `m.n` rectangular matrix (with `m > n`) and extract Q and R with reflection (since they are private fields), 
In this case, the result of $Q^T.Q$ is not identity matrix. Most of nonzeros off the diagonal of $Q^T.Q$. but i was thinking $Q^T.Q$ should not have any nonzero off the diagonal because of orthogonality. what am i missing?

Thanks

**Comment by wo80** [comment]
See https://github.com/wo80/CSparse.NET/issues/27 and https://gist.github.com/wo80/5a3fea8cb48196a1a11797a328aea33b
