### ISSUE TITLE
Preformance issues on large matrix

### ISSUE THREAD

**Issue by mac-cheroni** [wo80/CSparse.NET#6]
Hello, 
I'm trying to use your library to solve a large sparse matrix. Since I'm experimenting a performance issue, I would like to know if there is a fix or workaround to resolve it.

Particularly, I have noticed that almost all the CPU time is consumed by method _GraphHelper.DepthFirstSearch_ (see the attachment for details).

I'm wondering if there is an optimization problem or perhaps the algorithm is already optimized and there is nothing to do...?

Thank you very much,
Mac

![csparse](https://cloud.githubusercontent.com/assets/3083226/21577345/167b793a-cf58-11e6-876d-d19e2eb20ead.PNG)

**Comment by epsi1on** [comment]
i think it depends on your matrix.
How much is its dimensions? and its nonzero count? and how many seconds does takes long the execution of ```DepthFirstSearch()``` method?

**Comment by mac-cheroni** [comment]
My matrix is 30400x30400 with 100996 non zeroes. The matrix is symmetric and has a structure as shown below.
However, I have found that changing column ordering to MinimumDegreeAtA it works 10 times faster (now 2s for creation of matrix store, factorization and solving).

Anyway, since I'm solving for vectors in an iterative process, where the values of the matrix changes until convergence (but its structure remains the same), I'm asking if there is a way to symbolically factorize only once, at the beginning, and then, for each iteration, only substitute new values, calculate factors based on previous symbolic factorization and solve for a given vector...?
Thank you,
Mac

PS. my matrix structure:
![matrix](https://cloud.githubusercontent.com/assets/3083226/21580930/528806f2-d019-11e6-9592-c21f952d7f8c.PNG)

**Comment by epsi1on** [comment]
Sorry for late reply (after 8 months).
Anyways I would prefer to look at source code since it is open :)

> I'm asking if there is a way to symbolically factorize only once?

My answer is i think yes, assuming you use SparseCholesky, you can edit the method:

```C#
private void Factorize(CompressedColumnStorage<double> A, IProgress progress)
```
To:
```C#
public void Factorize(CompressedColumnStorage<double> A, IProgress progress)
```
(need recompile from source code)
And after first time of usage, only call this method from your code instead of creating a whole object from your code every time with this method:
```C#
public static SparseCholesky Create(CompressedColumnStorage<double> A, ColumnOrdering order, IProgress progress)
```
For a small test case (like 100x100 matrix etc.) please do a check using above method and compare it with creating whole object every time and see if result passed out from 
```C#
SparseCholesky.Solve(double[],double[])
```
of ```SparseCholesky```  method are same in both cases and let me know if it works.

Thanks

**Comment by wo80** [comment]
If this is still relevant, feel free to re-open the issue.

Some thoughts:
* The way SparseLU is implemented makes it hard (impossible?) to separate symbolic analysis and numeric factorization.
* If your matrix is positive definite, use SparseCholesky. As @epsi1on already pointed out, it should be easy to implement matrix refactorization.
* If your matrix is indefinite, you could try SparseLDL.
