### ISSUE TITLE
Intel MKL and CUDA for cholesky factorization

### ISSUE THREAD

**Issue by epsi1on** [wo80/CSparse.NET#9]
Hi,
You have any existing code that be able to use Intel's MKL or CUDA for cholesky factorization of a CompressedColumnStorage<Double> ?

**Comment by wo80** [comment]
Take a look at https://github.com/wo80/csparse-interop and the [test results](https://github.com/wo80/csparse-interop/wiki/Test-Results). The MKL PARDISO solver is really fast. But CHOLMOD comes close and it's small, so I'd prefer CHOLMOD .

I also did some tests with CUDA lately, but the code regularly crashes my display driver.

It's also part of the CSparse.Interop project, so lets move the discussion over there.
